package com.mo.mediaodyssey.shared.model;

import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;

import java.security.Principal;
import java.util.Collection;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import com.mo.mediaodyssey.auth.model.VerificationToken;
import com.mo.mediaodyssey.auth.model.PasswordResetToken;
import com.mo.mediaodyssey.layout.services.AvatarService;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

@Entity
@Table(name = "users")
public class User implements UserDetails {

    // ** Data Members **

    // Must be fixed. Randomly generated causes mismatch.
    private static final long serialVersionUID = 1L;

    /**
     * Id for MO User. Primary key. Automatically assigned.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Email address for MO User. Must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Username for MO User. By default, matches email address. Can be changed by MO
     * User. Does not need to be unique.
     * 
     * "username" is not used for authentication. Rather, email address is. Java
     * 
     * Security expects a unique Username and Password. "email" is unique but a
     * User's "username" is not. This is why "username" may appear in other places.
     * In those cases, outside of this class, an email address as "username" is
     * used.
     * 
     * TODO: logic to self-serve update a User details to be implemented in the
     * future.
     */
    @Column(nullable = false)
    private String username;

    /**
     * Password for MO User.
     */
    @Column(nullable = false)
    private String password;

    /**
     * isEnabled MO User. Used by Spring Security account-status checks.
     * 
     * By default, true, since account locking is handled separately.
     * 
     * Previously used for preventing log in if email is not verified. However, in
     * some situations, the visitor is unable to do so. Instead, we will now remind
     * visitors to verify their email when they log in, and allow them to log in
     * even if their email is not verified. This is to ensure visitors can still log
     * in and use the app. Email verification state is now managed below, with a
     * separate variable isEmailVerified.
     */
    @Column(nullable = false)
    private boolean isEnabled = true;

    /**
     * Email verification state for MO User.
     * By default, false, and flipped to true once verification succeeds.
     */
    @Column(nullable = false)
    private boolean isEmailVerified = false;

    /**
     * isAccountNonLocked MO User. Used to determine if MO User account has been not
     * locked by an Admin. By default, true (Account is not locked).
     * 
     * Logic handled in MOAuthenticationProvider. Adding more in the future requires
     * implementing its logic in MOAuthenticationProvider.
     */
    @Column(nullable = false)
    private boolean isAccountNonLocked = true;

    /**
     * Roles using SimpleGrantedAuthority
     * ROLE_USER,
     * ROLE_ADMIN
     */
    @Column(nullable = false)
    private String role = "ROLE_USER";

    /**
     * Authentication source for this account.
     * Expected values:
     * - LOCAL (email/password)
     * - OAUTH (external provider)
     */
    @Column(nullable = false)
    private String authProvider = "LOCAL";

    /**
     * OAuth provider registration id (e.g., google, github) when authProvider is
     * OAUTH.
     */
    @Column(nullable = true)
    private String oauthProvider;

    /**
     * Provider subject identifier (e.g., OpenID sub) when available.
     */
    @Column(nullable = true)
    private String oauthProviderUserId;

    /*
     *** Store the user's default avatar URL generated by API DiceBear.
     * This is for users who haven't uploaded any avatars + new users.
     * Unlike custom_avatar_URL, default_avatar_URL will always have a value.
     * It is generated when the user is created,
     */
    @Column(nullable = false)
    private String default_avatar_URL;

    /*
     * Storing user's upload avatar
     * users who don't set their avatar will be generated an avt from API
     * API DiceBear ensures the seed (use userEmail) always get the same avt. But
     * varies for each seeds.
     */
    @Column(nullable = true)
    private String custom_avatar_URL;

    /*
     * This variable is to determine which avatar type user is choosing to display.
     * This will be valuable for he header (goes to every thymeleaf page) +
     * userProfile.
     ** This variable will only store:
     * "custom" (custom_avatar_URL) or "default" (default_avatar_URL)
     * Notice: this will never be null (SHOULDN'T!)
     */
    @Column(nullable = false)
    private String selected_avatar_type;

    // ** Relationships **

    @OneToOne(mappedBy = "user", cascade = { CascadeType.PERSIST, CascadeType.REMOVE }, orphanRemoval = true)
    private VerificationToken verificationToken;

    @OneToOne(mappedBy = "user", cascade = { CascadeType.PERSIST, CascadeType.REMOVE }, orphanRemoval = true)
    private PasswordResetToken passwordResetToken;

    // ** Constructor, Getters, and Setters **
    public User() {
        // Required by JPA
    }

    // AuthService creates Account in registerUser() using this constructor.
    /*
     ** Logic from avatar side: when create user with email and password,
     * automatically let custom_Avatar_URL is null
     * and default_avatar_URL (generate avatar by using a uuid) and stored it.
     */
    public User(String email, String password) {
        this.email = email;
        this.username = email;
        this.password = password;
        this.isEnabled = true;
        this.isEmailVerified = false;
        this.isAccountNonLocked = true;
        this.role = "ROLE_USER";
        this.authProvider = "LOCAL";
        this.oauthProvider = null;
        this.oauthProviderUserId = null;

        /* their actual uploaded avatar pictures will be null until they upload */
        this.custom_avatar_URL = null;
        /* Default avatar for users who haven't uploaded any avatars + new users */
        this.default_avatar_URL = AvatarService.avatarGenerate(Math.abs(UUID.randomUUID().getMostSignificantBits()));
        /*
         * For new user, the selected_avatar (type) would always be default, until they
         * decide to change it
         */
        this.selected_avatar_type = "default"; // never let it null
    }

    // Used in DevUserService
    public User(String email, String username, String password, boolean isEnabled, boolean isEmailVerified,
            boolean isAccountNonLocked,
            String role, String authProvider, String oauthProvider, String oauthProviderUserId,
            String default_avatar_URL, String custom_avatar_URL, String selected_avatar_type) {
        this.email = email;
        this.username = username;
        this.password = password;
        this.isEnabled = isEnabled;
        this.isEmailVerified = isEmailVerified;
        this.isAccountNonLocked = isAccountNonLocked;
        this.role = role;
        this.authProvider = authProvider;
        this.oauthProvider = oauthProvider;
        this.oauthProviderUserId = oauthProviderUserId;
        this.custom_avatar_URL = custom_avatar_URL;
        this.default_avatar_URL = default_avatar_URL;
        this.selected_avatar_type = selected_avatar_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean isEnabled() {
        return isEnabled;
    }

    public void setEnabled(boolean isEnabled) {
        this.isEnabled = isEnabled;
    }

    public boolean isEmailVerified() {
        return isEmailVerified;
    }

    public void setEmailVerified(boolean isEmailVerified) {
        this.isEmailVerified = isEmailVerified;
    }

    @Override
    public boolean isAccountNonLocked() {
        return isAccountNonLocked;
    }

    public void setAccountNonLocked(boolean accountNonLocked) {
        isAccountNonLocked = accountNonLocked;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getAuthProvider() {
        return authProvider;
    }

    public void setAuthProvider(String authProvider) {
        this.authProvider = authProvider;
    }

    public String getOauthProvider() {
        return oauthProvider;
    }

    public void setOauthProvider(String oauthProvider) {
        this.oauthProvider = oauthProvider;
    }

    public String getOauthProviderUserId() {
        return oauthProviderUserId;
    }

    public void setOauthProviderUserId(String oauthProviderUserId) {
        this.oauthProviderUserId = oauthProviderUserId;
    }

    public boolean isOauthAccount() {
        return "OAUTH".equalsIgnoreCase(authProvider);
    }

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority(role));
    }

    public VerificationToken getVerificationToken() {
        return verificationToken;
    }

    public void setVerificationToken(VerificationToken verificationToken) {
        this.verificationToken = verificationToken;
    }

    public PasswordResetToken getPasswordResetToken() {
        return passwordResetToken;
    }

    public void setPasswordResetToken(PasswordResetToken passwordResetToken) {
        this.passwordResetToken = passwordResetToken;
    }

    public static long getSerialversionuid() {
        return serialVersionUID;
    }

    public String getCustom_avatar_URL() {
        return custom_avatar_URL;
    }

    public void setCustom_avatar_URL(String custom_avatar_URL) {
        this.custom_avatar_URL = custom_avatar_URL;
    }

    public String getDefault_avatar_URL() {
        return default_avatar_URL;
    }

    public void setDefault_avatar_URL(String default_avatar_URL) {
        this.default_avatar_URL = default_avatar_URL;
    }

    public String getSelected_avatar_type() {
        return selected_avatar_type;
    }

    public void setSelected_avatar_type(String selected_avatar_type) {
        this.selected_avatar_type = selected_avatar_type;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj instanceof User other) {
            return Objects.equals(this.email, other.email);
        }

        // Allow session principal matching across local User and OAuth principal types.
        if (obj instanceof Principal principal) {
            return Objects.equals(this.email, principal.getName());
        }

        return false;
    }

    @Override
    public int hashCode() {
        return Objects.hash(email);
    }
}