package com.mo.mediaodyssey.auth.services;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import com.mo.mediaodyssey.auth.security.AuthRateLimitDecision;
import com.mo.mediaodyssey.auth.security.AuthRateLimitScope;

import jakarta.annotation.PostConstruct;

@Repository
public class JdbcAuthRateLimitStore implements AuthRateLimitStore {

    private static final String BUCKET_TABLE = "auth_rate_limit_bucket";
    private static final String REQUEST_TABLE = "auth_rate_limit_request";
    private static final String REQUEST_LOOKUP_INDEX = "idx_auth_rate_limit_request_lookup";
    private static final String REQUEST_EXPIRY_INDEX = "idx_auth_rate_limit_request_expiry";

    private final JdbcTemplate jdbcTemplate;
    private final TransactionTemplate transactionTemplate;
    private final String schema;
    private final String bucketTable;
    private final String requestTable;
    private final ConcurrentMap<CacheKey, CachedDenial> denialCache = new ConcurrentHashMap<>();

    JdbcAuthRateLimitStore(JdbcTemplate jdbcTemplate,
            PlatformTransactionManager transactionManager,
            @Value("${spring.jpa.properties.hibernate.default_schema}") String schema) {
        this.jdbcTemplate = jdbcTemplate;
        this.transactionTemplate = new TransactionTemplate(transactionManager);
        this.schema = validateIdentifier(schema);
        this.bucketTable = qualify(BUCKET_TABLE);
        this.requestTable = qualify(REQUEST_TABLE);
    }

    /**
     * Creates the small rate-limit tables when the app starts.
     *
     * The main application already requires PostgreSQL. Keeping this schema local
     * to the store avoids another dependency while still sharing limits across app
     * instances.
     */
    @PostConstruct
    void initializeSchema() {
        jdbcTemplate.execute("CREATE SCHEMA IF NOT EXISTS " + schema);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS %s (
                    scope VARCHAR(32) NOT NULL,
                    client_key_hash CHAR(64) NOT NULL,
                    last_seen_millis BIGINT NOT NULL,
                    PRIMARY KEY (scope, client_key_hash)
                )
                """.formatted(bucketTable));
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS %s (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    scope VARCHAR(32) NOT NULL,
                    client_key_hash CHAR(64) NOT NULL,
                    requested_at_millis BIGINT NOT NULL
                )
                """.formatted(requestTable));
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS %s
                ON %s (scope, client_key_hash, requested_at_millis)
                """.formatted(REQUEST_LOOKUP_INDEX, requestTable));
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS %s
                ON %s (requested_at_millis)
                """.formatted(REQUEST_EXPIRY_INDEX, requestTable));
    }

    /**
     * Atomically checks every key for one scope and records the request if all
     * keys are still below the configured limit.
     *
     * The database is the source of truth so limits survive restarts and work
     * across app instances. The local cache only keeps short-lived denials, which
     * avoids repeated database work once a client is already over the limit.
     */
    @Override
    public AuthRateLimitDecision checkAndRecord(AuthRateLimitScope scope, List<String> clientKeys, int maxRequests,
            long windowMillis, long nowMillis) {
        List<String> clientKeyHashes = hashClientKeys(clientKeys);
        if (clientKeyHashes.isEmpty()) {
            return AuthRateLimitDecision.allowed();
        }

        AuthRateLimitDecision cachedDecision = cachedDenial(scope, clientKeyHashes, nowMillis);
        if (!cachedDecision.permitted()) {
            return cachedDecision;
        }

        Map<String, Long> deniedRetryAfterByHash = new HashMap<>();
        AuthRateLimitDecision decision = transactionTemplate.execute(status -> {
            long cutoffMillis = nowMillis - windowMillis;
            String scopeValue = scope.name();
            long retryAfterSeconds = 0L;

            upsertBuckets(scopeValue, clientKeyHashes, nowMillis);
            Map<String, RequestStats> requestStatsByHash = requestStats(scopeValue, clientKeyHashes, cutoffMillis);

            for (String clientKeyHash : clientKeyHashes) {
                RequestStats requestStats = requestStatsByHash.getOrDefault(clientKeyHash, RequestStats.empty());
                if (requestStats.requestCount() >= maxRequests) {
                    long retryAfterForKey = retryAfterSeconds(requestStats.oldestRequestMillis(), nowMillis,
                            windowMillis);
                    deniedRetryAfterByHash.put(clientKeyHash, retryAfterForKey);
                    retryAfterSeconds = Math.max(retryAfterSeconds, retryAfterForKey);
                }
            }

            if (retryAfterSeconds > 0L) {
                return AuthRateLimitDecision.denied(retryAfterSeconds);
            }

            insertRequests(scopeValue, clientKeyHashes, nowMillis);

            return AuthRateLimitDecision.allowed();
        });

        if (decision != null && decision.permitted()) {
            clearCachedDenials(scope, clientKeyHashes);
        } else if (decision != null) {
            cacheDenials(scope, deniedRetryAfterByHash, nowMillis);
        }
        return decision == null ? AuthRateLimitDecision.allowed() : decision;
    }

    /**
     * Removes all rows for the selected keys and scope.
     */
    @Override
    public void clear(AuthRateLimitScope scope, List<String> clientKeys) {
        List<String> clientKeyHashes = hashClientKeys(clientKeys);
        if (clientKeyHashes.isEmpty()) {
            return;
        }

        transactionTemplate.executeWithoutResult(status -> {
            jdbcTemplate.update("DELETE FROM " + requestTable + " WHERE scope = ? AND client_key_hash IN ("
                    + placeholders(clientKeyHashes.size()) + ")", scopeAndHashes(scope.name(), clientKeyHashes));
            jdbcTemplate.update("DELETE FROM " + bucketTable + " WHERE scope = ? AND client_key_hash IN ("
                    + placeholders(clientKeyHashes.size()) + ")", scopeAndHashes(scope.name(), clientKeyHashes));
        });
        clearCachedDenials(scope, clientKeyHashes);
    }

    /**
     * Removes the newest rows for the selected keys and scope.
     */
    @Override
    public void removeMostRecent(AuthRateLimitScope scope, List<String> clientKeys, int requestCount) {
        if (requestCount < 1) {
            return;
        }

        List<String> clientKeyHashes = hashClientKeys(clientKeys);
        if (clientKeyHashes.isEmpty()) {
            return;
        }

        transactionTemplate.executeWithoutResult(status -> {
            jdbcTemplate.update("""
                    DELETE FROM %s
                    WHERE id IN (
                        SELECT id
                        FROM (
                            SELECT id,
                                   ROW_NUMBER() OVER (
                                       PARTITION BY client_key_hash
                                       ORDER BY requested_at_millis DESC, id DESC
                                   ) AS row_number
                            FROM %s
                            WHERE scope = ? AND client_key_hash IN (%s)
                        ) ranked_requests
                        WHERE row_number <= ?
                    )
                    """.formatted(requestTable, requestTable, placeholders(clientKeyHashes.size())),
                    scopeHashesAndValue(scope.name(), clientKeyHashes, requestCount));
            touchBuckets(scope.name(), clientKeyHashes, 0L);
        });
        clearCachedDenials(scope, clientKeyHashes);
    }

    /**
     * Deletes expired request rows and then removes empty buckets that have not
     * been touched recently.
     */
    @Override
    public void cleanup(long expiredBeforeMillis, long staleBucketBeforeMillis, long nowMillis) {
        transactionTemplate.executeWithoutResult(status -> {
            jdbcTemplate.update("DELETE FROM " + requestTable + " WHERE requested_at_millis <= ?",
                    expiredBeforeMillis);
            jdbcTemplate.update("""
                    DELETE FROM %s b
                    WHERE b.last_seen_millis <= ?
                      AND NOT EXISTS (
                          SELECT 1
                          FROM %s r
                          WHERE r.scope = b.scope
                            AND r.client_key_hash = b.client_key_hash
                      )
                    """.formatted(bucketTable, requestTable), staleBucketBeforeMillis);
        });
        denialCache.entrySet().removeIf(entry -> entry.getValue().expiresAtMillis() <= nowMillis);
    }

    private AuthRateLimitDecision cachedDenial(AuthRateLimitScope scope, List<String> clientKeyHashes, long nowMillis) {
        long retryAfterSeconds = 0L;

        for (String clientKeyHash : clientKeyHashes) {
            CacheKey key = new CacheKey(scope, clientKeyHash);
            CachedDenial cachedDenial = denialCache.get(key);
            if (cachedDenial == null) {
                continue;
            }

            if (cachedDenial.expiresAtMillis() <= nowMillis) {
                denialCache.remove(key, cachedDenial);
                continue;
            }

            retryAfterSeconds = Math.max(retryAfterSeconds,
                    retryAfterSeconds(cachedDenial.expiresAtMillis(), nowMillis));
        }

        return retryAfterSeconds > 0L ? AuthRateLimitDecision.denied(retryAfterSeconds)
                : AuthRateLimitDecision.allowed();
    }

    private void cacheDenials(AuthRateLimitScope scope, Map<String, Long> deniedRetryAfterByHash, long nowMillis) {
        deniedRetryAfterByHash.forEach((clientKeyHash, retryAfterSeconds) -> denialCache.put(
                new CacheKey(scope, clientKeyHash), new CachedDenial(nowMillis + (retryAfterSeconds * 1_000L))));
    }

    private void clearCachedDenials(AuthRateLimitScope scope, List<String> clientKeyHashes) {
        for (String clientKeyHash : clientKeyHashes) {
            denialCache.remove(new CacheKey(scope, clientKeyHash));
        }
    }

    private void upsertBuckets(String scope, List<String> clientKeyHashes, long nowMillis) {
        String values = clientKeyHashes.stream()
                .map(ignored -> "(?, ?, ?)")
                .collect(Collectors.joining(", "));
        List<Object> parameters = new ArrayList<>(clientKeyHashes.size() * 3);
        for (String clientKeyHash : clientKeyHashes) {
            parameters.add(scope);
            parameters.add(clientKeyHash);
            parameters.add(nowMillis);
        }

        jdbcTemplate.update("""
                INSERT INTO %s (scope, client_key_hash, last_seen_millis)
                VALUES %s
                ON CONFLICT (scope, client_key_hash)
                DO UPDATE SET last_seen_millis = EXCLUDED.last_seen_millis
                """.formatted(bucketTable, values), parameters.toArray());
    }

    private Map<String, RequestStats> requestStats(String scope, List<String> clientKeyHashes, long cutoffMillis) {
        return jdbcTemplate.query("""
                SELECT client_key_hash, COUNT(*) AS request_count, MIN(requested_at_millis) AS oldest_request_millis
                FROM %s
                WHERE scope = ?
                  AND client_key_hash IN (%s)
                  AND requested_at_millis > ?
                GROUP BY client_key_hash
                """.formatted(requestTable, placeholders(clientKeyHashes.size())),
                resultSet -> {
                    Map<String, RequestStats> statsByHash = new HashMap<>();
                    while (resultSet.next()) {
                        statsByHash.put(resultSet.getString("client_key_hash"),
                                new RequestStats(resultSet.getInt("request_count"),
                                        resultSet.getLong("oldest_request_millis")));
                    }
                    return statsByHash;
                },
                scopeHashesAndValue(scope, clientKeyHashes, cutoffMillis));
    }

    private long retryAfterSeconds(long oldestRequest, long nowMillis, long windowMillis) {
        if (oldestRequest <= 0L) {
            return 1L;
        }

        long remainingMillis = oldestRequest + windowMillis - nowMillis;
        return Math.max(1L, (remainingMillis + 999L) / 1_000L);
    }

    private long retryAfterSeconds(long expiresAtMillis, long nowMillis) {
        return Math.max(1L, (expiresAtMillis - nowMillis + 999L) / 1_000L);
    }

    private void insertRequests(String scope, List<String> clientKeyHashes, long nowMillis) {
        String values = clientKeyHashes.stream()
                .map(ignored -> "(?, ?, ?)")
                .collect(Collectors.joining(", "));
        List<Object> parameters = new ArrayList<>(clientKeyHashes.size() * 3);
        for (String clientKeyHash : clientKeyHashes) {
            parameters.add(scope);
            parameters.add(clientKeyHash);
            parameters.add(nowMillis);
        }

        jdbcTemplate.update("""
                INSERT INTO %s (scope, client_key_hash, requested_at_millis)
                VALUES %s
                """.formatted(requestTable, values), parameters.toArray());
    }

    private void touchBuckets(String scope, List<String> clientKeyHashes, long nowMillis) {
        jdbcTemplate.update("""
                UPDATE %s
                SET last_seen_millis = ?
                WHERE scope = ? AND client_key_hash IN (%s)
                """.formatted(bucketTable, placeholders(clientKeyHashes.size())),
                valueScopeAndHashes(nowMillis, scope, clientKeyHashes));
    }

    private String hashClientKey(String clientKey) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(clientKey.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException ex) {
            throw new IllegalStateException("SHA-256 is required for auth rate-limit keys.", ex);
        }
    }

    private List<String> hashClientKeys(List<String> clientKeys) {
        return clientKeys.stream()
                .map(this::hashClientKey)
                .distinct()
                .sorted()
                .toList();
    }

    private String placeholders(int count) {
        return String.join(", ", Collections.nCopies(count, "?"));
    }

    private Object[] scopeAndHashes(String scope, List<String> clientKeyHashes) {
        List<Object> parameters = new ArrayList<>(clientKeyHashes.size() + 1);
        parameters.add(scope);
        parameters.addAll(clientKeyHashes);
        return parameters.toArray();
    }

    private Object[] scopeHashesAndValue(String scope, List<String> clientKeyHashes, Object value) {
        List<Object> parameters = new ArrayList<>(clientKeyHashes.size() + 2);
        parameters.add(scope);
        parameters.addAll(clientKeyHashes);
        parameters.add(value);
        return parameters.toArray();
    }

    private Object[] valueScopeAndHashes(Object value, String scope, List<String> clientKeyHashes) {
        List<Object> parameters = new ArrayList<>(clientKeyHashes.size() + 2);
        parameters.add(value);
        parameters.add(scope);
        parameters.addAll(clientKeyHashes);
        return parameters.toArray();
    }

    private record CacheKey(AuthRateLimitScope scope, String clientKeyHash) {
    }

    private record CachedDenial(long expiresAtMillis) {
    }

    private record RequestStats(int requestCount, long oldestRequestMillis) {
        private static RequestStats empty() {
            return new RequestStats(0, 0L);
        }
    }

    private String qualify(String tableName) {
        return schema + "." + tableName;
    }

    private String validateIdentifier(String identifier) {
        if (identifier == null || !identifier.matches("[A-Za-z_][A-Za-z0-9_]*")) {
            throw new IllegalArgumentException("Database schema name must be a simple SQL identifier.");
        }

        return identifier;
    }
}
